version: "3.6"

services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker/portainer/data:/data
            - ./docker/shared:/shared
        environment:
            - TZ=${TZ}
    # mariadb:
    #     image: mariadb:10.5.2
    #     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    #     restart: always
    #     volumes:
    #         - mariadb:/var/lib/mysql
    #     environment:
    #         TZ: ${TZ}
    #         MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    #         MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    #         MYSQL_USER: /run/secrets/mysql_user
    #         MYSQL_PASSWORD: /run/secrets/mysql_password
    #         MYSQL_DATABASE: /run/secrets/mysql_db
    #     env_file:
    #         - mariadb.env
    postgres:
        image: postgres:alpine
        restart: always
        volumes:
            - ./nextcloud/postgres:/var/lib/postgresql/data
        env_file:
            - postgres.env
    app:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - ./nextcloud:/var/www/html
        environment:
            - POSTGRES_HOST=postgres
            - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
            - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
        env_file:
            - postgres.env
        ports:
            - 443:443
        depends_on:
            - postgres
    web:
        build: ./web
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nextcloud:/var/www/html:ro
        depends_on:
            - app
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - postgres:db
        ports:
            - 8081:80
        depends_on:
            - postgres

secrets:
    nextcloud_admin_password:
        file: ./secrets/nextcloud_admin_password.txt
    nextcloud_admin_user:
        file: ./secrets/nextcloud_admin_user.txt
    mysql_db:
        file: ./secrets/mysql_db.txt
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt
    mysql_user:
        file: ./secrets/mysql_user.txt
    mysql_password:
        file: ./secrets/mysql_password.txt
    postgres_db:
        file: ./secrets/postgres_db.txt
    postgres_password:
        file: ./secrets/postgres_password.txt
    postgres_user:
        file: ./secrets/postgres_user.txt
